/**
 * The one PNG reader/writer for generated bytes.
 *
 * Every stage of the read is bounded before it allocates or inflates —
 * encoded size, IHDR geometry, chunk lengths and CRCs, compression/filter
 * methods, the inflate output length, and each scanline's filter code — so
 * bytes that crossed an external-provider trust boundary can never exhaust
 * memory or be mis-measured. Two callers share this reader: the true-alpha
 * gate (`alpha.ts`) and the matting pass (`matte.ts`); adding a third read
 * site must never mean writing a third parser.
 *
 * The reader normalizes at one boundary: whatever 8-bit non-interlaced
 * channel layout arrives (grayscale, RGB, grayscale+alpha, RGBA) comes back
 * as RGBA, so no downstream reader needs to know about alternate layouts.
 * Anything that cannot be measured — JPEG, palette, interlaced, 16-bit — is
 * refused, never guessed.
 */
import { deflateSync, inflateSync } from "node:zlib";

const SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

/** Encoded-size cap — an external image larger than this is never parsed. */
export const MAX_ENCODED_BYTES = 64 * 1024 * 1024;
/** Per-axis dimension cap (PNG spec max is 2^31−1; nothing thumbnail-shaped needs more). */
export const MAX_DIMENSION = 8192;
/** Pixel-count cap — bounds the decoded scanline buffer and the output allocation. */
export const MAX_PIXELS = 16_777_216;

/** A refusal reason from the parser; callers wrap it in their own contract error. */
export class PngParseError extends Error {}

const fail = (why: string): never => {
  throw new PngParseError(why);
};

export interface PngHeader {
  width: number;
  height: number;
  bitDepth: number;
  colorType: number;
  interlace: number;
}

export interface DecodedPng {
  width: number;
  height: number;
  /** The declared color type, before channel expansion. */
  colorType: number;
  /** Pixels expanded to RGBA, 4 bytes per pixel, row-major. */
  rgba: Buffer;
}

// CRC-32 (PNG polynomial), bit-reflected table form — verifies every chunk.
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(data: Buffer): number {
  let c = 0xffffffff;
  for (let i = 0; i < data.length; i++) c = CRC_TABLE[(c ^ data[i]!) & 0xff]! ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function asBuffer(bytes: Uint8Array): Buffer {
  return Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength);
}

/**
 * Read and bound-check the IHDR only — no allocation, no inflate. Callers
 * that have a policy about the color type (the alpha gate does) apply it
 * between this and `decodePng`.
 */
export function readPngHeader(bytes: Uint8Array): PngHeader {
  if (bytes.byteLength > MAX_ENCODED_BYTES)
    fail(
      `the candidate is ${(bytes.byteLength / 1024 / 1024).toFixed(1)} MB — over the ${MAX_ENCODED_BYTES / 1024 / 1024} MB parse limit`,
    );
  const buf = asBuffer(bytes);
  if (buf.length < 8 || !buf.subarray(0, 8).equals(SIGNATURE))
    fail("the bytes are not a PNG (bad signature)");
  if (buf.toString("ascii", 12, 16) !== "IHDR")
    fail("the PNG has no IHDR header where one is required");

  const width = buf.readUInt32BE(16);
  const height = buf.readUInt32BE(20);
  const bitDepth = buf[24]!;
  const colorType = buf[25]!;
  const compressionMethod = buf[26]!;
  const filterMethod = buf[27]!;
  const interlace = buf[28]!;
  if (width === 0 || height === 0)
    fail(`the PNG declares a zero dimension (${width}×${height}) — not a real image`);
  if (width > MAX_DIMENSION || height > MAX_DIMENSION)
    fail(`the PNG declares ${width}×${height} — over the ${MAX_DIMENSION}px per-axis parse limit`);
  if (width * height > MAX_PIXELS)
    fail(
      `the PNG declares ${width}×${height} — over the ${MAX_PIXELS.toLocaleString("en-US")}-pixel parse limit`,
    );
  if (compressionMethod !== 0)
    fail(`unknown IHDR compression method ${compressionMethod} — corrupt or non-standard PNG`);
  if (filterMethod !== 0)
    fail(`unknown IHDR filter method ${filterMethod} — corrupt or non-standard PNG`);
  if (bitDepth !== 8) fail(`bit depth ${bitDepth} is not supported — 8-bit PNG only`);
  if (interlace !== 0) fail("interlaced PNG is not supported");
  return { width, height, bitDepth, colorType, interlace };
}

/** Bytes per pixel for each supported 8-bit color type; palette (3) is unsupported. */
const CHANNELS: Record<number, number> = { 0: 1, 2: 3, 4: 2, 6: 4 };

/**
 * Decode an 8-bit non-interlaced PNG to RGBA. Every bound in `readPngHeader`
 * applies, plus chunk CRCs, a capped inflate, and per-scanline filter codes.
 */
export function decodePng(bytes: Uint8Array): DecodedPng {
  const { width, height, colorType } = readPngHeader(bytes);
  const channels = CHANNELS[colorType];
  if (channels === undefined)
    fail(
      colorType === 3
        ? "palette PNG (color type 3) is not supported"
        : `color type ${colorType} is not supported`,
    );
  const buf = asBuffer(bytes);

  const idat: Buffer[] = [];
  let off = 8;
  while (off + 12 <= buf.length) {
    const len = buf.readUInt32BE(off);
    if (off + 12 + len > buf.length)
      fail(
        `chunk "${buf.toString("ascii", off + 4, off + 8)}" declares ${len} bytes past the end of the file (corrupt PNG)`,
      );
    const type = buf.toString("ascii", off + 4, off + 8);
    // The CRC covers the chunk type plus its data.
    if (crc32(buf.subarray(off + 4, off + 8 + len)) !== buf.readUInt32BE(off + 8 + len))
      fail(`chunk "${type}" fails its CRC-32 check (corrupt PNG)`);
    if (type === "IDAT") idat.push(buf.subarray(off + 8, off + 8 + len));
    if (type === "IEND") break;
    off += 12 + len;
  }
  if (idat.length === 0) fail("the PNG has no IDAT image data");

  const stride = width * channels!;
  const expectedRaw = height * (stride + 1);
  let raw: Buffer;
  try {
    // Bounded inflate: the stream may not produce more than the declared
    // geometry needs, so a decompression bomb cannot allocate past the cap.
    raw = inflateSync(Buffer.concat(idat), { maxOutputLength: expectedRaw });
  } catch {
    fail("the IDAT stream does not decompress to the declared pixel data (corrupt or oversized PNG)");
  }
  if (raw!.length !== expectedRaw)
    fail("the IDAT stream length does not match the declared pixel data (corrupt PNG)");

  const paeth = (a: number, b: number, c: number) => {
    const p = a + b - c;
    const pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
    return pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
  };

  const plane = Buffer.alloc(height * stride);
  let pos = 0;
  for (let y = 0; y < height; y++) {
    const filter = raw![pos++]!;
    if (filter > 4) fail(`scanline ${y} uses unknown filter code ${filter} (corrupt PNG)`);
    const cur = plane.subarray(y * stride, (y + 1) * stride);
    const prev = y > 0 ? plane.subarray((y - 1) * stride, y * stride) : null;
    for (let x = 0; x < stride; x++) {
      const a = x >= channels! ? cur[x - channels!]! : 0;
      const b = prev ? prev[x]! : 0;
      const c = prev && x >= channels! ? prev[x - channels!]! : 0;
      let v = raw![pos + x]!;
      if (filter === 1) v += a;
      else if (filter === 2) v += b;
      else if (filter === 3) v += (a + b) >> 1;
      else if (filter === 4) v += paeth(a, b, c);
      cur[x] = v & 0xff;
    }
    pos += stride;
  }

  // Normalize every layout to RGBA once, here — downstream readers never
  // branch on the channel count.
  if (channels === 4) return { width, height, colorType, rgba: plane };
  const rgba = Buffer.alloc(width * height * 4);
  for (let i = 0, o = 0; o < rgba.length; i += channels!, o += 4) {
    if (channels === 1) {
      rgba[o] = rgba[o + 1] = rgba[o + 2] = plane[i]!;
      rgba[o + 3] = 255;
    } else if (channels === 2) {
      rgba[o] = rgba[o + 1] = rgba[o + 2] = plane[i]!;
      rgba[o + 3] = plane[i + 1]!;
    } else {
      rgba[o] = plane[i]!;
      rgba[o + 1] = plane[i + 1]!;
      rgba[o + 2] = plane[i + 2]!;
      rgba[o + 3] = 255;
    }
  }
  return { width, height, colorType, rgba };
}

/**
 * Write RGBA pixels as an 8-bit non-interlaced PNG (filter 0 scanlines) —
 * the shape `decodePng` and the true-alpha gate read back.
 */
export function encodePngRgba(width: number, height: number, rgba: Buffer): Buffer {
  if (rgba.length !== width * height * 4)
    throw new Error(`encodePngRgba: ${rgba.length} bytes is not ${width}×${height} RGBA`);
  const stride = width * 4;
  const raw = Buffer.alloc(height * (stride + 1));
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0; // filter: none
    rgba.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // color type: RGBA
  return Buffer.concat([
    SIGNATURE,
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw)),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

function chunk(type: string, data: Buffer): Buffer {
  const head = Buffer.alloc(4);
  head.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([head, body, crc]);
}
